---
all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

  hosts:
    server1:
      ansible_host: 54.91.213.200
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
