---
all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

  hosts:
    server1:
      ansible_host: 3.92.182.189
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
