name: Build Template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Display echo file
        uses: docker://wehostasia/ansible:2.8
        run: ansible --version

  pre-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Display preprod
        run: echo "Pre production deploy"
