name: Build Template

on: [push, pull_request]

jobs:

  prebuild:
    name: "Pre deploy server"
    runs-on: ubuntu-latest
    container:
      image: wehostasia/ansible:2.8
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1
      - name: Add ssh private key
        run: |
          mkdir -p /root/.ssh && chmod 700 /root/.ssh
          echo "${{ secrets.SSH_SERVER1 }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa

      - name: Display echo file
        shell: bash
        run: ansible-playbook config/ansible/playbook.yml -vv
