name: Build Template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  prebuild:
    runs-on: ubuntu-latest
    container:
      image: wehostasia/ansible:2.8
    steps:
      - name: Display echo file
        run: ansible --version
