name: Build Template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  prebuild:
    runs-on: ubuntu-latest
    container:
      image: wehostasia/ansible:2.8
    steps:
      - uses: actions/checkout@v1
      - name: Add ssh private key
        env:
          SSH_RSA: ${{ secrets.SSH_SERVER1 }}
        run: printf $SSH_RSA
        shell: bash
#          mkdir -p ~/.ssh && chmod 700 ~/.ssh
#          mkdir -p ~/.ansible && chmod 755 ~/.ansible
#          echo $SSH_RSA > ~/.ssh/id_rsa
#          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#          chmod 600 ~/.ssh/config

#      - name: Show Directories and Files
#        run: |
#          ls -la ~/.ssh/id_rsa
#          cat ~/.ssh/id_rsa
#
#      - name: Display echo file
#        run: ansible-playbook config/ansible/playbook.yml -vv
