name: Build Template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Display echo file
        run: echo "Build Template"

  pre-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Display preprod
        run: echo "Pre production deploy"
